spring:
  application:
    name: P2PVisio
  jmx:
    default-domain: p2pvis
  # This is for disable security - Comment the following if you want to use security
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  profiles:
    active: dev
  datasource:
    jdbc-url: jdbc:sqlserver://USCLED444.agna.amgreetings.com:62220;databaseName=CommonSQLDevPrj
    username: yyywildflyd287
    password: YYY@wildflyd287
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    minimum-idle: 0
    maximum-pool-size: 1
    idle-timeout: 60000
    max-lifetime: 900000
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: false
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    database: SQL_SERVER
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_second_level_cache: false
      hibernate.enable_lazy_load_no_trans: true
      hibernate.show_sql: false
      hibernate.format_sql: true
      hibernate.use_sql_comments: false
      #hibernate.generate_statistics: true
  jta:
    enabled: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

server:
  port: 8084
  servlet:
    context-path: /p2pvis

management:
  endpoints:
    web:
      exposure:
        include:
        - loggers
        - health
        - info
        - metrics
        - env
  endpoint:
    env:
      enabled: true
    loggers:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
    metrics:
      enabled: true